### ISSUE TITLE
Configure the mock IDP to return data similar to HAKA

### ISSUE THREAD

**Issue by totutotu** [UniversityOfHelsinkiCS/DEFA#28]
The data we wish to receive from Haka is in the form:

cn: To identify the user
displayName: To identify the user
eduPersonPrimaryOrgUnitDN: To identify the organization of the user
mail: To contact the user if required
schacHomeOrganization: To identify the organization of the user
schacPersonalUniqueCode: To identify the user within his organization

**Comment by laimikko1** [comment]
Our mock idp, that we use locally, now returns the data in a similar format to our HAKA service.
