### ISSUE TITLE
Defa-staging server files to correct place

### ISSUE THREAD

**Issue by totutotu** [UniversityOfHelsinkiCS/DEFA#33]
Now defa-staging files are somewhere where the 'defa-user' doesn't have write access which makes things unnecessarily complicated. 

Transfer everything to /home/defa-user/defa-staging.cs.helsinki.fi/

**Comment by laimikko1** [comment]
We created a separate defa-staging folder that the defa-user owns and moved all necessary files to that. We can now remove the old solution.
